# Site settings
title: Will Merrill
author: Will Merrill
author_avatar: https://vignette4.wikia.nocookie.net/ageofempiresonline/images/a/a4/Harjar.png/revision/latest?cb=20121105021202
email: william.merrill@yale.edu
description: Personal website and blog. Thanks for stopping by!
baseurl: "" # optional
url: "https://viking-sudo-rm.github.io"
#twitter_username: foo_bar
github_username: viking-sudo-rm
github_repo: viking-sudo-rm/viking-sudo-rm.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
